In [0]:
import numpy as np

ข้อ 1 จงเขียน array ที่มีแต่เลข 0 แบบ vector 10 ตัว และ แบบ Matrix 4x4

In [30]:
print('array ที่มีแต่เลข 0 แบบ vector 10 ตัว   ',np.zeros(10))
print('array ที่มีแต่เลข 0 แบบ Matrix 4x4  ')
print(np.zeros((4,4)))

array ที่มีแต่เลข 0 แบบ vector 10 ตัว    [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array ที่มีแต่เลข 0 แบบ Matrix 4x4  
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ข้อ 2 จงเขียน array ที่มีแต่เลข 1 แบบ vector 5 ตัว และ แบบ Matrix 3x3

In [37]:
print('array ที่มีแต่เลข 1 แบบ vector 5 ตัว  ',np.ones(5))
print('array ที่มีแต่เลข 1 แบบ Matrix 3x3  ')
print(np.ones((3,3)))

array ที่มีแต่เลข 1 แบบ vector 5 ตัว   [1. 1. 1. 1. 1.]
array ที่มีแต่เลข 1 แบบ Matrix 3x3  
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


ข้อ 3 จงเขียน array ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง

In [39]:
a = np.random.randint(10,99,20)**2
print(a)

[ 729 4761 6724 1764 2500 1521 1936 4624 2025 2116  529 6241 2601 4489
 4900 7744 1369 9604 1296 7569]


ข้อ 4 จงเขียน array ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง แต่เขียนแบบ List comprehension

In [41]:
a = np.random.randint(10,99,20)
b = [i**2 for i in a]
print(b)

[576, 8464, 4761, 784, 7056, 9025, 144, 5476, 7921, 7921, 169, 3844, 729, 196, 2304, 1225, 9604, 1089, 7744, 4356]


ข้อ 5 นำข้อ 3 และ 4 มาเปรียบเวลากัน โดยใช้ฟังก์ชั่น time.time( ) เพื่อจับเวลา แสดงผลลัพธ์ในรูปแบบมิลลิวินาที

In [44]:
import time
time1 = time.time()
a = np.random.randint(10,99,20)**2
time2 = time.time()

time3 = time.time()
c = np.random.randint(10,99,20)
d = [i**2 for i in c]
time4 = time.time()

print('จับเวลา พบว่า ข้อสามใช้เวลา {} ข้อสี่ใช้เวลา {}'.format(time2-time1,time4-time3))

จับเวลา พบว่า ข้อสามใช้เวลา 0.0003123283386230469 ข้อสี่ใช้เวลา 0.00044727325439453125


ข้อ 6 จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลข 10 ถึง 1000

In [0]:
np.arange(10,1001)

ข้อ 7 จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคู่ 10 ถึง 2000

In [0]:
np.arange(10,2001,2)

ข้อ 8 จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคี่ 12 ถึง 900

In [0]:
np.arange(13,901,2)

ข้อ 9 จงสร้าง identity matrix แบบ 4x4

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

ข้อ 10 จงหาว่า array ที่มีสมาชิก 100 ตัว เริ่มจาก 5 ถึง 25 มีผลต่างแต่ละตัวเท่ากับเท่าใด

In [19]:
a = np.linspace(5,25,100)
print(a)

[ 5.          5.2020202   5.4040404   5.60606061  5.80808081  6.01010101
  6.21212121  6.41414141  6.61616162  6.81818182  7.02020202  7.22222222
  7.42424242  7.62626263  7.82828283  8.03030303  8.23232323  8.43434343
  8.63636364  8.83838384  9.04040404  9.24242424  9.44444444  9.64646465
  9.84848485 10.05050505 10.25252525 10.45454545 10.65656566 10.85858586
 11.06060606 11.26262626 11.46464646 11.66666667 11.86868687 12.07070707
 12.27272727 12.47474747 12.67676768 12.87878788 13.08080808 13.28282828
 13.48484848 13.68686869 13.88888889 14.09090909 14.29292929 14.49494949
 14.6969697  14.8989899  15.1010101  15.3030303  15.50505051 15.70707071
 15.90909091 16.11111111 16.31313131 16.51515152 16.71717172 16.91919192
 17.12121212 17.32323232 17.52525253 17.72727273 17.92929293 18.13131313
 18.33333333 18.53535354 18.73737374 18.93939394 19.14141414 19.34343434
 19.54545455 19.74747475 19.94949495 20.15151515 20.35353535 20.55555556
 20.75757576 20.95959596 21.16161616 21.36363636 21

In [22]:
print('ผลต่างของค่าระหว่างสมาชิกใน array ที่อยู่ติดกัน มีขนาดเท่ากับ {}'.format(a[2]-a[1]))

ผลต่างของค่าระหว่างสมาชิกใน array ที่อยู่ติดกัน มีขนาดเท่ากับ 0.20202020202020154


ข้อ 11 จงเขียนฟังก์ชั่น random ตัวเลขแบบ float ในช่วง 0-1 ขึ้นมา 1 ตัว

In [23]:
np.random.random(1)

array([0.85301568])

ข้อ 12 จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose

In [27]:
a = np.random.randint(50,100,(4,4))
print(a)
print('a transpose')
print(a.T)

[[68 89 63 81]
 [83 80 56 51]
 [62 96 93 65]
 [50 65 76 58]]
a transpose
[[68 83 62 50]
 [89 80 96 65]
 [63 56 93 76]
 [81 51 65 58]]


กำหนดให้ array ต่อไปนี้ใช้กับโจทย์ข้อ 13 - 17

In [31]:
a= np.arange(1,26).reshape((5,5))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


ข้อ 13 ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14

In [32]:
a[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

ข้อ 14 ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20

In [35]:
a[3,2:]

array([18, 19, 20])

ข้อ 15 ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22

In [37]:
a[3:,0:2]

array([[16, 17],
       [21, 22]])

ข้อ 16 ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3

In [38]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

ข้อ 17 จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา

In [39]:
a= np.arange(1,26).reshape((5,5))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


ข้อ 18 จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มี
ค่ามากกว่า 50 และปริ้นออกมา

In [43]:
arr = np.random.randint(10,100,(5,5))
print(arr)

[[76 75 92 40 19]
 [36 70 60 59 62]
 [98 99 71 31 86]
 [57 18 89 99 80]
 [65 10 45 74 86]]


In [44]:
print(arr[arr>50])

[76 75 92 70 60 59 62 98 99 71 86 57 89 99 80 65 74 86]


ข้อ 19 จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ conditional selection เช็คว่าตัว
ใดบ้างมีค่ามากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา 

ขอใช้ matrix จาก ข้อ 18

In [48]:
listA = [i for i in arr[arr>40]]
print('ค่าทีมากกว่า 40 ในรูปของ list  ',listA)

ค่าทีมากกว่า 40 ในรูปของ list   [76, 75, 92, 70, 60, 59, 62, 98, 99, 71, 86, 57, 89, 99, 80, 65, 45, 74, 86]


ข้อ 20 เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมา
ทำเป็น matrix 3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)

In [0]:
def inputKrab(x):
  while x<10 or x>100:
    x=int(input('10<ค่า<100 .. ป้อนใหม่ '))
  return x  

In [61]:
b20 = []
for i in range(9):
  a = int(input('ค่า '))
  a = inputKrab(a)
  b20.append(a)
c20 = np.array(b20).reshape((3,3))
print('array c20 แบบ 3x3 ')
print(c)
print('................................')
print('c transpose')
print(c.T)
print('................................')


ค่า 11
ค่า 12
ค่า 13
ค่า 1
10<ค่า<100 .. ป้อนใหม่ 2
10<ค่า<100 .. ป้อนใหม่ 3
10<ค่า<100 .. ป้อนใหม่ 14
ค่า 15
ค่า 16
ค่า 17
ค่า 18
ค่า 19
array c20 แบบ 3x3 
[[11 12 13]
 [14 15 16]
 [17 18 19]]
................................
c transpose
[[11 14 17]
 [12 15 18]
 [13 16 19]]
................................


In [68]:
print('เลขที่อยู่ตำแหน่ง 2, 2 คือ' ,c[2,2].T)

เลขที่อยู่ตำแหน่ง 2, 2 คือ 19
